//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiitSocioApis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Allocation
    {
        public int id { get; set; }
        public string emp_no { get; set; }
        public string course_no { get; set; }
        public string semester_no { get; set; }
        public string section { get; set; }
        public string Discipline { get; set; }
        public Nullable<int> semC { get; set; }
        public string SOS { get; set; }
    }
}
