//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiitSocioApis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chat
    {
        public string userid { get; set; }
        public string chat_id { get; set; }
        public int id { get; set; }
        public string dateTime { get; set; }
        public string text { get; set; }
        public string type { get; set; }
        public Nullable<int> chatTo { get; set; }
        public string Date { get; set; }
        public string url { get; set; }
    }
}
