//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiitSocioApis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DateeSheet
    {
        public int id { get; set; }
        public string Time { get; set; }
        public string examType { get; set; }
        public string venue { get; set; }
        public string section { get; set; }
        public string paper { get; set; }
        public string day { get; set; }
    }
}
