//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiitSocioApis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public int id { get; set; }
        public string Admin { get; set; }
        public string name { get; set; }
        public string profile { get; set; }
        public Nullable<bool> isOfficial { get; set; }
        public string date { get; set; }
        public Nullable<int> memberCount { get; set; }
        public string description { get; set; }
    }
}
