//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiitSocioApis.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BIITSOCIOEntities : DbContext
    {
        public BIITSOCIOEntities()
            : base("name=BIITSOCIOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Allocation> Allocations { get; set; }
        public virtual DbSet<chat> chats { get; set; }
        public virtual DbSet<commentsOn> commentsOns { get; set; }
        public virtual DbSet<course> courses { get; set; }
        public virtual DbSet<crsEnrp> crsEnrps { get; set; }
        public virtual DbSet<DateeSheet> DateeSheets { get; set; }
        public virtual DbSet<Diary> Diaries { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<FriendRequest> FriendRequests { get; set; }
        public virtual DbSet<GroupChat> GroupChats { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<JoinedSociety> JoinedSocieties { get; set; }
        public virtual DbSet<notification> notifications { get; set; }
        public virtual DbSet<Post> Posts { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<React> Reacts { get; set; }
        public virtual DbSet<SharedPost> SharedPosts { get; set; }
        public virtual DbSet<Society> Societies { get; set; }
        public virtual DbSet<Story> Stories { get; set; }
        public virtual DbSet<student> students { get; set; }
        public virtual DbSet<Teacher> Teachers { get; set; }
        public virtual DbSet<Timetable> Timetables { get; set; }
        public virtual DbSet<UserGroup> UserGroups { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
