//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiitSocioApis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class notification
    {
        public int id { get; set; }
        public string body { get; set; }
        public string title { get; set; }
        public string NotificationTo { get; set; }
        public Nullable<int> status { get; set; }
        public string dateTime { get; set; }
        public string type { get; set; }
        public Nullable<int> post_id { get; set; }
        public Nullable<int> fromWall { get; set; }
        public Nullable<bool> ifOfficial { get; set; }
        public string notificationFrom { get; set; }
    }
}
