//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiitSocioApis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int id { get; set; }
        public string postedBy { get; set; }
        public string dateTime { get; set; }
        public string text { get; set; }
        public string type { get; set; }
        public string postFor { get; set; }
        public string description { get; set; }
        public Nullable<int> likesCount { get; set; }
        public Nullable<int> CommentsCount { get; set; }
        public string user { get; set; }
        public string status { get; set; }
        public string fromWall { get; set; }
    }
}
