//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiitSocioApis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SharedPost
    {
        public Nullable<int> postId { get; set; }
        public int id { get; set; }
        public Nullable<int> sharedBy { get; set; }
        public Nullable<int> sharedTo { get; set; }
    }
}
