//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiitSocioApis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Story
    {
        public int id { get; set; }
        public string type { get; set; }
        public Nullable<int> societyId { get; set; }
        public string url { get; set; }
        public string text { get; set; }
        public Nullable<int> color { get; set; }
        public string time { get; set; }
        public string storyFor { get; set; }
    }
}
