//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiitSocioApis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public string aridNo { get; set; }
        public string cnic { get; set; }
        public string section { get; set; }
        public string sonOf { get; set; }
    }
}
