//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiitSocioApis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string CNIC { get; set; }
        public string name { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public string profileImage { get; set; }
        public string phone { get; set; }
        public string userType { get; set; }
        public string token { get; set; }
        public string lastLogged { get; set; }
        public string TAOf { get; set; }
        public string CrOf { get; set; }
        public string aridNo { get; set; }
        public string sonOf { get; set; }
        public string section { get; set; }
        public string isTeachingTo { get; set; }
    }
}
